//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_Form.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public string leaID { get; set; }
        public string schoolID { get; set; }
        public string name { get; set; }
        public string organizationType { get; set; }
        public string gradesOffered { get; set; }
        public string streetLine1 { get; set; }
        public string streetLine2 { get; set; }
        public string city { get; set; }
        public string stateProvince { get; set; }
        public string postalCode { get; set; }
        public string county { get; set; }
        public string NCESID_district { get; set; }
        public string NCESID_school { get; set; }
        public string code1 { get; set; }
        public string code2 { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_updated { get; set; }
        public string FL_grade_code { get; set; }
        public string FL_school_type { get; set; }
        public string FL_charter_school_status { get; set; }
        public string FL_region_code { get; set; }
    
        public virtual District District { get; set; }
    }
}
