//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_Form.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int staffID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string positionTitle { get; set; }
        public string leaID { get; set; }
        public string schoolID { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string code1 { get; set; }
        public string code2 { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_updated { get; set; }
    }
}
